export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const FETCH_DATA_START="FETCH_DATA_START";
export const FETCH_DATA_END="FETCH_DATA_END";


export const CREATE_COLLECTION="CREATE_COLLECTION";
export const UPDATE_COLLECTION="UPDATE_COLELCTION";
export const DELETE_COLLECTION="DELETE_COLLECTION";
export const GET_ALL_COLLECTION="GET_ALL_COLLECTION";
export const GET_COLLECTION_BY_USER="GET_COLLECTION_BY_USER";
export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE";
export const BOOKLIST_COLLECTION="BOOKLIST COLLECTION";
export const BOOKLIST_COLLECTION_SPECIFIC="BOOKLIST COLLECTION_SPECIFIC";
export const BOOK_DETAIL_SINGLE="BOOK_DETAIL_SINGLE";

export const CREATE_COLLECTION_FAIL="CREATE_COLLECTION_FAIL";
export const UPDATE_COLLECTION_FAIL="UPDATE_COLELCTION_FAIL";
export const DELETE_COLLECTION_FAIL="DELETE_COLLECTION_FAIL";
export const GET_ALL_COLLECTION_FAIL="GET_ALL_COLLECTION_FAIL";
export const GET_COLLECTION_BY_USER_FAIL="GET_COLLECTION_BY_USER_FAIL";
export const UPDATE_USER_PROFILE_FAIL="UPDATE_USER_PROFILE_FAIL";
export const BOOKLIST_COLLECTION_FAIL="BOOKLIST COLLECTION_FAIL";
export const BOOKLIST_COLLECTION_SPECIFIC_FAIL="BOOKLIST COLLECTION_SPECIFIC_FAIL";
export const BOOK_DETAIL_SINGLE_FAIL="BOOK_DETAIL_SINGLE_FAIL";


export const BOOKLIST_COLLECTION_BUSINESS='BOOKLIST_COLLECTION_BUSINESS';
export const BOOKLIST_COLLECTION_FICTION='BOOKLIST_COLLECTION_FICTION';
export const BOOKLIST_COLLECTION_NON_FICTION='BOOKLIST_COLLECTION_NON_FICTION';
export const BOOKLIST_COLLECTION_HUMOR='BOOKLIST_COLLECTION_HUMOR';
export const BOOKLIST_COLLECTION_ADVENTURE='BOOKLIST_COLLECTION_ADVENTURE';
export const BOOKLIST_COLLECTION_BIOGRAPHY='BOOKLIST_COLLECTION_BIOGRAPHY';
export const BOOKLIST_COLLECTION_ROMANCE='BOOKLIST_COLLECTION_ROMANCE';

export const BOOKLIST_COLLECTION_ROMANCE_FAIL='BOOKLIST_COLLECTION_ROMANCE_FAIL';
export const BOOKLIST_COLLECTION_BUSINESS_FAIL='BOOKLIST_COLLECTION_BUSINESS_FAIL';
export const BOOKLIST_COLLECTION_FICTION_FAIL='BOOKLIST_COLLECTION_FICTION_FAIL';
export const BOOKLIST_COLLECTION_NON_FICTION_FAIL='BOOKLIST_COLLECTION_NON_FICTION_FAIL';
export const BOOKLIST_COLLECTION_HUMOR_FAIL='BOOKLIST_COLLECTION_HUMOR_FAIL';
export const BOOKLIST_COLLECTION_ADVENTURE_FAIL='BOOKLIST_COLLECTION_ADVENTURE_FAIL';
export const BOOKLIST_COLLECTION_BIOGRAPHY_FAIL='BOOKLIST_COLLECTION_BIOGRAPHY_FAIL';